retrieve_news_task:
  description: >
    Retrieve top news headlines of the past 24 hours.
  expected_output: >
    The list of 5 websites with the top headlines of the past 24 hours.
  agent: retrieve_news

website_scrape_task:
  description: >
    Scrape the website for the latest news and information.
  expected_output: >
    Fully scraped websites with all the important information from the website.
  agent: website_scraper

ai_news_write_task:
  description: >
    Summarize the information from the websites into a top headline and a less than 50-word description for each headline.
  expected_output: >
    The 5 latest top headlines of the past 24 hours and description in less than 50 words for each headline.
    Formatted as markdown without '```'.
  agent: ai_news_writer

file_write_task:
  description: >
    Write the news headlines and description of each headline to a file.
  expected_output: >
    A list of 5 top headlines and description of each headline in less than 50 words from previous task into a file named news/{date}_news.md.
  agent: file_writer